### ISSUE TITLE
Update readme to use Poser nuget package instead of Pose

### ISSUE THREAD

**Issue by motcke** [Miista/pose#28]

**Comment by Miista** [comment]
@motcke I believe I updated the README. Did I miss a spot?

Oh. I just realized that you probably meant the README in the NuGet package?

**Comment by motcke** [comment]
I'm talking about this

![image](https://github.com/Miista/pose/assets/3529897/0468b214-94b5-44ce-b104-a6ad905b525b)

**Comment by Miista** [comment]
Oh. Yes. That should definitely be fixed. Thank you for pointing it out.
