### ISSUE TITLE
Question related to debugger

### ISSUE THREAD

**Issue by edwin-alvarez** [Miista/pose#47]
I read we cannot debug, 

but in this example, I don't have any shim for MyClass.DoSomething2 . why the debugger is not hitting line 21

![image](https://github.com/Miista/pose/assets/5774873/e9596ad0-42b4-465d-b366-b300f1b455d8)

**Comment by Miista** [comment]
@edwin-alvarez This is because `DoSomething2` is invoked from inside the isolated code (`PoseContext.Isolate`). Any code being isolated is actively rewritten and any breakpoints within that code cannot be reached.

I hope that answers your question.

**Comment by Miista** [comment]
@edwin-alvarez I am closing this issue. Please reach out if the above does not answer your question.
